# -*- coding: utf-8 -*-
"""pandas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_PGeHMELTXwpxSUjFo-nlSkG1ov-Dwws
"""

!pip install transformers torch pandas

from transformers import pipeline
import pandas as pd
#load sentiment analysis model
sentiment=pipeline("sentiment-analysis")
#sample product review
reviews="""The laptop starts quickly and works smoothly for dialy tasks.
The screen quality is clear and good for watching videos.
Battery backup is average and needs charging often.
The fan makes noise when many apps are running.
overall,it is a good laptop for students but not for gaming.
"""
#split review into sentences
sentences=reviews.split(".")
pros=[]
cons=[]
for s in sentences:
  s=s.strip()
  if s==" ":
    continue
    result=sentiment(s)[0]
    if result["label"]=="POSITIVE":
      pros.append(s)
    elif result["label"]=="NEGATIVE":
        cons.append(s)
        #take only 2 pros and 2 cons
        pros=pros[:2]
        cons=cons[:2]
        #create table
        df=pd.DataFrame({
            "pros":pros,
            "cons":cons
        })
        df