# -*- coding: utf-8 -*-
"""Text generation code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vBQDNrfhhkBlPPTsXgvT4jF7Eoumhdvr
"""

!pip install transformers torch





from transformers import pipeline
#load text generation model(genAI)
generator = pipeline(
    "text-generation",
    model="gpt2"
)
#input prompt
prompt="Artificial Intelligence in finance will"
#generate text
result=generator(prompt,max_length=50,num_return_sequences=1)
print("AI Generated Text:")
print(result[0]['generated_text'])